### ISSUE TITLE
Update the dataset

### ISSUE THREAD

**Issue by umaar** [Houshalter/amabot#1]
Hey! Nice work! Would you be able to update the dataset please?

**Comment by Houshalter** [comment]
I'm sorry to say this project is dead. The code was just thrown together quickly and is a mess. I haven't run it in 2 years. I'm thinking of redoing the whole thing and making it more sane.

**Comment by umaar** [comment]
Oh ok, would you mind letting me know the current 'architecture' and what needs changing, might give it a go myself! :D

**Comment by umaar** [comment]
Hey again! I'm working on a simple web interface for this, it's looking ok but a lot of the answers to questions are nonsensical. Do you think I need to add a bigger training dataset?

**Comment by umaar** [comment]
Was fun to play around with anyway!

**Comment by umaar** [comment]
Btw, is interesting to see ChatGPT in relation to this, so many years later!
